### PR TITLE
Handle situation when “headers” is None.

### PR DESCRIPTION
**Pull request by whisller**
I have lambda function that runs behind private api gateway.
It looks that for this case `headers` is being set to None.

### CODE REVIEW

**Comment by mikegrima** [comment]
The tests are all failing because of issues with Moto at the moment.

@whisller Please increment the version number to `0.1.10` in https://github.com/Netflix-Skunkworks/raven-python-lambda/blob/master/raven_python_lambda/__about__.py, and I will push this out.

**Comment by whisller** [comment]
@mikegrima done!

**Comment by mikegrima** [comment]
@whisller Actually -- stupid question, is `headers` missing -- or -- is `headers` present in the `dict`, but set to `None`?

If the latter, the code above will still return `None`.

**Comment by whisller** [comment]
@mikegrima `headers` key is present but set to `None`. I'd rather keep it this way so in sentry you can see that `host` is not being set and act upon it accordingly.

**Comment by mikegrima** [comment]
The code as submitted would raise an exception, since if `headers` is set to `None`, then `event.get('headers', {})` would return `None`, not `{}`. It would only return `{}` if `headers` was absent in the `dict`.

For example:
```
>>> foo = {'key': None}
>>> print(foo.get('key', {}))
None
>>> foo.get('key', {}).get('bar', {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'get'
>>> print(foo.get('bar', {}))
{}
```

It's a nasty gotcha in Python.

**Comment by whisller** [comment]
Oh, I've missed this one! Blaming that it was late :D Fixing that!

**Comment by whisller** [comment]
@mikegrima sir, have a look please :)

**Comment by mikegrima** [comment]
Yup, that should work.

**Comment by mikegrima** [comment]
Pushed 0.1.10 out to PyPI.

**Comment by whisller** [comment]
@mikegrima cheers!

**Pull request merged**
